name: Benchmark

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: configure
      # cross-compiling flags set to avoid regular expression backend error: https://github.com/google/benchmark/issues/773
      run: cmake -Hbenchmark -Bbuild -DCMAKE_CROSSCOMPILING=1 -DRUN_HAVE_STD_REGEX=0 -DRUN_HAVE_POSIX_REGEX=0

    - name: build
      run: cmake --build build -j4

    - name: run
      run: ./build/EasyIteratorBenchmark
