name: Benchmark

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: configure
      run: cmake -Hbenchmark -Bbuild

    - name: build
      run: cmake --build build -j4

    - name: run
      run: ./build/EasyIteratorBenchmark
