name: Benchmark

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: install dependencies # https://stackoverflow.com/questions/35898748/error-using-clang-to-compile-c
      run: |
        sudo bash -c "cat >> /etc/apt/sources.list" << LLVMAPT
        # LLVM
        deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty main
        deb-src http://llvm.org/apt/trusty/ llvm-toolchain-trusty main
        # 3.5 
        deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.5 main
        deb-src http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.5 main
        # 3.6 
        deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.6 main
        deb-src http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.6 main
        LLVMAPT

        wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -

        sudo apt-get update -y
        sudo apt-get install -y clang-3.6 lldb-3.6 libc++-dev libc++abi-dev

    - name: configure
      # flags set to avoid strange regular expression backend error: https://github.com/google/benchmark/issues/773
      run: cmake -Hbenchmark -Bbuild -DRUN_HAVE_STD_REGEX=0 -DRUN_HAVE_POSIX_REGEX=0

    - name: build
      run: cmake --build build -j4

    - name: run
      run: ./build/EasyIteratorBenchmark
