name: MacOS

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: configure
      run: cmake -Htest -Bbuild

    - name: build
      run: cmake --build build --config Debug -j4

    - name: test
      run: |
        cd build
        ctest --build-config Debug
