name: Style

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install format dependencies
      run: pip3 install clang-format==14.0.6 cmake_format==0.6.11 pyyaml

    - name: configure
      run: cmake -Stest -Bbuild

    - name: check style
      run: cmake --build build --target check-format
